package-lock.json, package.json, src/pages/mypage/MypageComponent.js, src/pages/signup/SignupComponent.js
- mypage에서 회원정보를 받아올때 pw 없이 받아오게함
- signup 페이지에서 console.log 삭제
=> [fix] mypage Password_Hide

src/App.js, src/components/alert/AlertModalOfClickBasketButton.css, src/components/alert/AlertModalOfClickBasketButton.js, src/pages/basket/ListToBasketComponent.js, src/pages/order/OrderComponent.js, src/pages/product/ProductDetailComponent.js
=> [test] PR test giuk

src/pages/order/OrderComponent.js
=> test PR 테스트

src/pages/login/LoginComponent.js, src/pages/login/modal/FindIdModal.js
=> [feature] create FindId/PwModal

src/App.js, src/pages/order/OrderAtom.js, src/pages/order/OrderComponent.js, src/pages/product/ProductDetailComponent.js
- 제품목록상세페이지에서 바로 구매 버튼 클릭 시 
리코일을 사용하여 선택된 제품 정보가 임시 저장되서 주문페이지에 넘어감
=> [feat] productDetail

package-lock.json, package.json, src/pages/basket/BasketAtom.js, src/pages/basket/ListToBasketComponent.js
- 장바구니페이지에서 픽업 주문하기 버튼 클릭 시 
리코일 사용하여 주문페이지에 선택된 제품 목록들이 주문페이지에 임시저장됨.
=> [feat] basket

src/pages/product/AllProductComponent.css, src/pages/product/AllProductComponet.js
- 선택된 카테고리를 저장하는 selectedCategory 상태 변수 추가
- 각 버튼의 onClick 이벤트에서 selectedCategory를 업데이트
- selectedCategory와 일치하는 버튼에만 selected 클래스를 동적으로 할당해서,
- css에서 버튼을 클릭했을 때와 아닐 때의 스타일에 변화를 줌
- allProducts 함수 내에서 setSelectedCategory('와인 전체')를 명시적으로 호출해야 다시 버튼이 클릭됨.
=> [fix] 가로형 카테고리바

src/App.js, src/pages/category/CategoryComponent.js, src/pages/product/AllProductComponet.js, src/pages/product/ProductDetailComponent.js
- 제품별 1차 카테고리에 설정 후 > 버튼 클릭 시 1차 카테고리에 해당하는 2차 카테고리들과 함께 그에 맞는 제품목록들이 보여짐
=> [feature] 제품별 카테고리 설정

src/App.js, src/pages/product/AllProductComponet.js, src/pages/product/ProductDetailComponent.js
- 제품사진 클릭했을 때 제춤자세히보기 페이지 오류가 있었는데 URL에 category1을 추가해 오류 해결
=> [fix] DetailProduct

src/pages/home/HomeComponent.js, src/pages/home/MyPlaceComponent.css, src/pages/home/MyPlaceComponent.js
- 해당부분에 로그아웃/로그인 전후에 따른 주소정보가 다르게 뜨게 수정
=> [fix] 메인홈화면 상단 위치정보 보이는 부분 ( refix )

src/App.js, src/pages/category/CategoryComponent.js, src/pages/product/AllProductComponet.js
- 카테고리2 항목 클릭 시에 카테고리2 항목에 맞는 제품페이지로 이동
=> [feat] Category

src/pages/basket/ListToBasketComponent.css, src/pages/basket/ListToBasketComponent.js, src/pages/product/ProductDetailComponent.css
- 오늘픽업/예약픽업을 탭바로 구성
- 총 수량/ 총 가격 / 픽업 주문하기 버튼 하단에 sticky로 레이어 상단에 고정
- 수량 증가/감소 기능 버튼 추가
- 상단 네비게이션 바 추가
=> [feature] 장바구니 화면 구성 수정

src/App.js, src/pages/search/SearchComponent.css, src/pages/search/SearchComponent.js
- search 폴더와 SearchComponent 파일 생성
- App.js 파일에 <SearchComponent /> 삽입
- 간단한 검색 기능 구현
- 필터링을 이용하여 제품 카테고리별로 검색어를 입력하면 결과 출력
=> [feature] 검색 기능 구현

src/App.js, src/pages/category/CategoryComponent.js, src/pages/home/HomeComponent.js, src/pages/product/AllProductComponent.js, src/pages/product/CategoriesProductComponent.css, src/pages/product/CategoriesProductComponent.js, src/pages/product/ProductDetailComponent.js
- 메인화면에서 전체상품 클릭 시 category1별로 전체상품 나옴. AllProductComponent
- 메인화면에서 카테고리 클릭 후 category2에 해당하는 상품페이지 나옴. CategoriesProductComponent
- 제품사진 클릭 시 제품상세페이지 오류 있던거 수정
=> [feat] 전체제품페이지 및 카테고리별제품페이지

src/App.js, src/components/footer/FooterComponent.js, src/pages/history/HistoryComponent.css, src/pages/history/HistoryComponent.js
- pages / history / HistoryComponent.js 와 .css 파일 생성
- App.js 파일에 <HistoryComponent /> 추가
- 상단 nav bar 생성
- 오늘픽업 / 예약픽업 탭바 생성
- 고객정보에서 주문갯수 불러와서 (  ) 에 출력하는거 일단 쿠폰 데이터 불러와서 출력함
- 하단 nav bar 생성
- 중앙 메인 컨테이너 생성
=> [feature] 주문내역

src/pages/category/CategoryComponent.css, src/pages/category/CategoryComponent.js
- 버튼 :hover 효과로 커서를 올리면 버튼의 색상이 변하도록 함
- 전체적인 화면 디자인 수정
=> [fix] 버튼 효과 수정 및 전체적인 화면 수정

src/pages/category/CategoryComponent.js, src/pages/product/CategoriesProductComponent.js
- 메인홈페이지에서 카테고리 클릭했을 때 2차 카테고리 클릭만 되었는데, 1차 카테고리까지 클릭할 수 있게 수정
=> [fix] category

src/App.js, src/pages/basket/ListToBasketComponent.js, src/pages/order/OrderComponent.js
=> [fix] basket

src/pages/basket/ListToBasketComponent.js, src/pages/product/AllProductComponent.js, src/pages/product/CategoriesProductComponent.js, src/pages/product/ProductDetailComponent.js
-  제품 가격에 000가 형성될때마다  "," 추가해주기
=> [fix] price

package-lock.json, package.json, src/App.js, src/pages/admin/PickupCompletedPageComponent.css, src/pages/admin/PickupCompletedPageComponent.js, src/pages/admin/ShowOrdersPageComponent.css, src/pages/admin/ShowOrdersPageComponent.js, src/pages/order/OrderComponent.js, src/pages/product/ProductDetailComponent.js
- 관리자페이지에서 즉시픽업페이지와 즉시픽업 완료내역페이지를 만들고 백엔드와 연동 완료
=> [feat] 관리자페이지 즉시픽업 페이지 기능 구현

src/pages/order/NaverMapContainer.js, src/pages/order/OrderComponent.css, src/pages/order/OrderComponent.js
=> [fix] OrderComponent.js

package-lock.json, package.json, src/pages/home/HomeComponent.js, src/pages/login/LoginComponent.js, src/pages/login/LogoutComponent.js, src/pages/login/kakao/KakaoLoginHandler.js, src/pages/setPlace/SetPlaceComponent.js
- 로그인, 위치+매장변경 시에 해당 정보들이 로컬스토리지에 업데이트 되게 변경
- 최선의 방법이라 생각됨
=> [fix] localStorage에 위치,매장정보 추가

src/pages/product/AllProductComponent.js, src/pages/product/CategoriesProductComponent.js
- 서버에서 localStorage의 storeId(사용자 단골매장)을 통해 Inventory를 가져오고 해당 매장의 제품(재고가 >0)인 제품들에는 '오늘픽업' 마크가 뜨게함
- 좌측 상단의 오늘픽업 필터링 버튼을 통해 '오늘픽업' 마크가 붙은 제품만 보여주게함
- 카테고리랑 모든제품보기 페이지가 각각 있어서 둘다 적용함 => 컴포넌트로 분리해도 될듯함
=> [feature] 오늘픽업 마크 및 필터링 기능 추가

src/pages/history/HistoryComponent.css, src/pages/history/HistoryComponent.js
- 주문내역 내용 부분 수정 중
- 주문내역에 맞는 서버 주소로 변경 필요함
=> [feature] 주문내역 (수정 중)

src/App.js, src/pages/admin/AdminOrderComponent.css, src/pages/admin/AdminOrderComponent.js
=> feat 관리자 발주페이지

src/pages/admin/AdminOrderComponent.js, src/pages/order/OrderComponent.js
- 결제 시 orderDate로부터 +2일로 pickupDate 삽입되도록 수정
- 발주 시 로컬스토리지 저장된 storeId 사용하도록 수정
=> [fix] 결제시 pickupDate 삽입, 로컬스토리지 storeId 사용

src/pages/basket/ListToBasketComponent.js, src/pages/order/OrderComponent.js
ListToBasketComponent.js에서 즉시/예약픽업 상품 분류
-체크박스 수정해야함
=> feat 장바구니에서 예약픽업/즉시픽업 분류

src/pages/admin/AdminComponent.js, src/pages/admin/AdminOrderComponent.css, src/pages/admin/AdminOrderComponent.js, src/pages/admin/ShowReservationPickupComponent.js
- AllProductComponent 와 classname이 중복되어 오류 발생
- AdminOrderComponent classname은 모든 classname 앞에 adminoder 붙여서 수정
- AdminComponent / ShowReservationPickupComponent 일부 수정
=> [fix] AdminOrderComponent classname  변경

src/components/footer/FooterComponent.css, src/pages/product/CategoriesProductComponent.css, src/pages/search/SearchComponent.css, src/pages/search/SearchComponent.js
- 기존 오늘픽업/제품목록 띄우기
- 검색엔진은 시간이 부족한 관계로 시간남으면 진행
=> [feature] 검색API 연동 및 디자인수정

src/pages/order/OrderAtom.js, src/pages/order/OrderComponent.js, src/pages/product/ProductDetailComponent.js
- 제품상세보기 페이지에서 바로 구매 클릭 시 제품 정보와 함께 픽업 유형도 나오도록 수정
=> [fix] 바로구매 버튼 수정

src/pages/order/OrderComponent.js
- 코드 합치고 난 후에, 서로 코드 누락된 부분 수정
=> [fix] 주문페이지

src/pages/admin/AdminComponent.js, src/pages/admin/ShowReservationPickupComponent.js
- 관리자페이지 중에 즉시발주신청페이지 빠져있어서 포함시킨 후 올림.
=> [fix] 관리자페이지

src/components/alert/AlertModalOfClickBasketButton.css, src/components/alert/AlertModalOfClickBasketButton.js
- AlertModalOfClickBasketButton 에서  className="modal-container" / overlayClassName="modal-overlay"  추가하고
- css에서 모달 창이 항상 중앙애 배치되도록 수정
=> [fix] 모달 창 항상 중앙에 배치하도록 수정
